config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dental#index'
  resources :dental

  resources :quiz

  get '/babyteeth' => 'tutorial#babyteeth'
  get '/cav_intro' => 'tutorial#cav_intro'
  get '/cav_form_1' => 'tutorial#cav_form_1'
  get '/cav_form_2' => 'tutorial#cav_form_2'
  get '/cav_form_3' => 'tutorial#cav_form_3'
  get '/cav_form_4' => 'tutorial#cav_form_4'
  get '/cav_prev_1' => 'tutorial#cav_prev_1'
  get '/cav_prev_2' => 'tutorial#cav_prev_2'
  get '/cav_prev_3' => 'tutorial#cav_prev_3'

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dental_controller.rb
class DentalController < ApplicationController
	def index
		@user = current_user
		if @user
			@profile = @user.profile
		end
	end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
	def new
		@result = Result.new
	end

	def create
		@result = Result.new(result_params)
	end

	def result_params
		params.require(:result).permit(:age, :gender, :role, :raw_score, :percentage)
	end
end

app/controllers/tutorial_controller.rb
class TutorialController < ApplicationController
	def babyteeth
	end

	def cav_intro
	end

	def cav_form_1
	end

	def cav_form_2
	end

	def cav_form_3
	end

	def cav_form_4
	end

	def cav_prev_1
	end

	def cav_prev_2
	end

	def cav_prev_3
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dental/index.html.erb
<html>
<head>
	<title>Taking Care of Your Child's Teeth</title>
</head>
<body>
	<header>
		<% if !user_signed_in? %>
		<div class="nav">
			<ul>
				<li><%= link_to 'Home', dental_index_path %></li>
				<li><%= link_to 'Sign Up', new_user_registration_path %></li>
				<li><%= link_to "Sign In", new_user_session_path %></li>
			</ul>
		<% end %>
		</div>
		<% if user_signed_in? and current_user.profile and current_user.profile.role == 'p_parent' %>
		<div class="nav">
			<ul>
				<li><%= link_to 'Home', dental_index_path %></li>
				<li><%= link_to "Profile", profile_path(@profile) %></li>
				<li><%= link_to "My Children", profile_children_path(@profile) %></li>
		</div>
		<% end %>
		<% if user_signed_in? and current_user.profile and current_user.profile.role == 'staff' %>
		<div class="nav">
			<ul>
				<li><%= link_to 'Home', dental_index_path %></li>
				<li><%= link_to "Profile", profile_path(@profile) %></li>

			</ul>
		</div>
		<% end %>
	</header>
<h1>Taking Care of your Child's Teeth: An Introduction</h1>

<% if !user_signed_in? %>
	<p>Want to manage your child's dental health? <%= link_to 'Sign up here!', new_user_registration_path %></p>
	<p>Coming back to add more data? <%= link_to "Please sign in!", new_user_session_path %></p>
<% else %>

<% if !current_user.profile %>
	<p><%= link_to "Create Your Profile", new_profile_path %></p>
<% else current_user.profile %>
	<p><%= link_to "View Your Profile", profile_path(@profile) %></p>
<% end %>
	<% if current_user.profile and current_user.profile.role == 'p_parent' %>
		<p><%= link_to "My Children", profile_children_path(@profile) %></p>
	<% end %>
<% end %>

<%= link_to "Take the Tutorial!", babyteeth_path %><br><br>
<header>
<div class="user-info">
	<ul>
		<% if user_signed_in? and @user.profile %>
			<li><%= @user.profile.name %></li>
			<li><%= @user.email %></li>
			<li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
		<% end %>
	</ul>
</div>
</header>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mchdentorial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/tutorial/_menubar.html.erb
	<header>
		<% if !user_signed_in? %>
		<div class="nav">
			<ul>
				<li><%= link_to 'Home', dental_index_path %></li>
				<li><%= link_to 'Sign Up', new_user_registration_path %></li>
				<li><%= link_to "Sign In", new_user_session_path %></li>
			</ul>
		<% end %>
		</div>
		<% if user_signed_in? and current_user.profile and current_user.profile.role == 'p_parent' %>
		<div class="nav">
			<ul>
				<li><%= link_to 'Home', dental_index_path %></li>
				<li><%= link_to "Profile", profile_path(@profile) %></li>
				<li><%= link_to "My Children", profile_children_path(@profile) %></li>
		</div>
		<% end %>
		<% if user_signed_in? and current_user.profile and current_user.profile.role == 'staff' %>
		<div class="nav">
			<ul>
				<li><%= link_to 'Home', dental_index_path %></li>
				<li><%= link_to "Profile", profile_path(@profile) %></li>
			</ul>
		</div>
		<% end %>
	</header>

app/views/tutorial/babyteeth.html.erb
<%= render 'menubar' %>
<h2>The Importance of Baby Teeth</h2>
<p>Baby teeth play a vital role in holding the space for permanent teeth. In addition, they allow your child to eat and learn to talk.</p>

<header>
<div class="tut-nav">
	<ul>
		<li><%= link_to 'Home', dental_index_path %></li>
		<li><%= link_to "Next: Cavities", cav_intro_path %><li>
	</ul>
</div>
</header>

app/views/tutorial/cav_form_1.html.erb
<%= render 'menubar' %>
<h2>Cavities</h2>
<h3>How do they form?</h3>
<h4>Poor Oral Hygiene</h4>
<p>Once a child has a cavity, it is more likely that the child will develop more cavities because the bacteria spread from one tooth to another. One way to detect if you child is prone to cavities is visible plaque on the upper front teeth. Plaque is a soft, sticky biofilm made up of bacteria and bacterial products, is off white to light yellow in color, and usually starts building up closest to the gums. </p>
<br>
<footer>
	<div class="tut-nav">
		<ul>
			<li><%= link_to "What Cavities Are", cav_intro_path %></li>
			<li><%= link_to "Cavity Formation: Part 2", cav_form_2_path %></li>
		</ul>
	</div>
</footer>

app/views/tutorial/cav_form_2.html.erb
<%= render 'menubar' %>
<h2>Cavities</h2>
<h3>How do they form?</h3>
<h4>Diet</h4>
<p>Sugars throughout the day can also cause cavities to form, so limit your child’s sugar intake to meal times and avoid sugars at snack times. Candy, sweets, and desserts are one form of sugar, but juice, soda and other sweet drinks are another way sugar is introduced into the child’s diet. Juice consumption should be limited to 4-6 ounces per day and only with meals. Drinking water and eating healthy snacks such as fruits and vegetables can help prevent cavities.</p>
<br>
<br>
<%= image_tag "cocacola.JPG" %>
<%= image_tag "orange_juice.JPG" %>
<br><br><br><br>

<header>
<div class="tut-nav">
	<ul>
		<li><%= link_to "Cavity Formation: Part 1", cav_form_1_path %></li>
		<li><%= link_to "Cavity Formation: Part 3", cav_form_3_path %><li>
	</ul>
</div>
</header>

app/views/tutorial/cav_form_3.html.erb
<%= render 'menubar' %>

<h2>Cavities</h2>
<h3>How do they form?</h3>
<h4>Milk at Night</h4>
<p>Although milk is healthy to help your child grow, your child should not take a bottle of milk or breast milk to bed. If your child drinks milk before bed, it is important to brush their teeth AFTER to prevent cavities from forming. Only water is allowed after brushing your child’s teeth at night.</p>
<br>


<header>
<div class="tut-nav">
	<ul>
		<li><%= link_to "Cavity Formation: Part 2", cav_form_2_path %></li>
		<li><%= link_to "Cavity Formation: Part 4", cav_form_4_path %><li>
	</ul>
</div>
</header>

app/views/tutorial/cav_form_4.html.erb
<%= render 'menubar' %>

<h2>Cavities</h2>
<h3>How do they form?</h3>
<h4>Transmission through Food Sharing</h4>
<p>Since cavities can transfer from person to person, it is important not to share food or utensils with your child, or allow siblings to share with each other, because bacteria can spread between mouths. Also, address your own dental needs and maintain good oral hygiene to reduce the child’s exposure to cavity-causing bacteria.</p>
<br>

<header>
<div class="tut-nav">
	<ul>
		<li><%= link_to "Cavity Formation: Part 3", cav_form_3_path %></li>
		<li><%= link_to "Next: Cavity Prevention", cav_prev_1_path %></li>
	</ul>
</div>
</header>

app/views/tutorial/cav_intro.html.erb
<%= render 'menubar' %>

<h2>Cavities</h2>
<h3>What are they?</h3>
Bacteria in our mouth break down sugars and produce acid leading to cavities. Cavities appear as white, yellow, brown, or black spots on the front or tops of teeth.

<header>
<div class="tut-nav">
	<ul>
		<li><%= link_to "Back to baby teeth", babyteeth_path %></li>
		<li><%= link_to "Next: How do they form?", cav_form_1_path %><li>
	</ul>
</div>
</header>

app/views/tutorial/cav_prev_1.html.erb
<%= render 'menubar' %>

<h2>Cavities</h2>
<h3>How do we prevent them?</h3>
<h4>Fluoride!</h4>
<p>Fluoride is like a vitamin for teeth! Miami-Dade county has safe levels in the water, so it is a good idea to give your child tap water.</p>



<header>
<div class="tut-nav">
	<ul>
		<li><%= link_to "Back to Cavity Formation: Part 4", cav_form_4_path %></li>
		<li><%= link_to "Next: Cavity Prevention: Part 2", cav_prev_2_path %></li>
	</ul>
</div>
</header>

app/views/tutorial/cav_prev_2.html.erb
<%= render 'menubar' %>

<h2>Cavities</h2>
<h3>How do we prevent them?</h3>
<h4>Brushing!</h4>
<p>If your child is under 6.5 years old, you should brush with your child for two minutes in the morning and before bed. Below this age, they usually don’t have the manual dexterity to brush by themselves. Toothpaste should contain fluoride, and using a smear of toothpaste for children aged 0-2 and a pea-sized amount for children aged 2-5 will protect your child’s teeth.</p>

<header>
<div class="tut-nav">
	<ul>
		<li><%= link_to "Cavity Prevention: Part 1", cav_prev_1_path %></li>
		<li><%= link_to "Cavity Prevention: Part 3", cav_prev_3_path %><li>
	</ul>
</div>
</header>

app/views/tutorial/cav_prev_3.html.erb
<%= render 'menubar' %>
<h2>Cavities</h2>
<h3>How do we prevent them?</h3>
<h4>Regular Dental Checkups</h4>
<p>Make sure you have a dental home where you can take your child for regular visits every 6 months. At the dentist you can receive counseling about appropriate diet, oral hygiene and oral development. The dentist will also take x-rays and do a thorough clinical exam to catch the cavities while they are small. This can help prevent the spread of cavities to other teeth.</p>

<header>
<div class="tut-nav">
	<ul>
		<li><%= link_to "Cavity Prevention: Part 3", cav_prev_3_path %></li>
		<li><%= link_to "Home", dental_index_path %></li>
	</ul>
</div>
</header>